### PR TITLE
Dml commands

### PR DESCRIPTION
**Pull request by rajuTK9**
In this PR, I have covered the concept of `DML_commands`

I created demo entries in all the tables.

Please check out this video for an explanation [here.](https://youtu.be/Lu_fgcY7z-g)

Thank you!

### CODE REVIEW

**Review by th3c0d3br34ker — COMMENTED** [review]
thanks @rajuTK9 for your submission. i reviewed your self-viva. 

as i understand this PR is to highlight `DML commands`. 
DML commands include not just `INSERT`.  

consider exploring what all `DML commands` are available and  demonstrate at least 3 of them in the PR.

**Comment by rajuTK9** [comment]
> thanks @rajuTK9 for your submission. i reviewed your self-viva.
> 
> as i understand this PR is to highlight `DML commands`. DML commands include not just `INSERT`.
> 
> consider exploring what all `DML commands` are available and demonstrate at least 3 of them in the PR.

Thanks for the feedback Jainam. I have made the changes as suggested. 
Please have a look at the new self-viva video [here](https://youtu.be/Lu_fgcY7z-g) with the implementation of Insert, Select, Update, and Delete commands.

**Review by th3c0d3br34ker — APPROVED** [review]
thanks @rajuTK9 for reverting, the explanation was elaborate. 

please consider the following points:

1. the self-viva is not just a walk-through of your code.
2. the self-viva should have some basic definition of the concerned topic, which needs to be highlighted. (in this case `DML Commands`)

for upcoming PRs please keep this points in mind while recording the self-viva.

you may merge this PR.

**Comment by rajuTK9** [comment]
Thank you! Will take care of these in next PRs.

**Pull request merged**
