### PR TITLE
#1. Schema and ERD

### PR DESCRIPTION
**Pull request by rajuTK9**
This PR includes:
- ERD of the project
- Schema Diagram of the project

The concepts achieved in this PR are:
1. Schema and ERD

### CODE REVIEW

**Comment by Kalvium-Program** [comment]
1. Add schema diagram
2. Include loom explanation video
3. consider combining the tables expense and income, as transaction, you can have a column which indicates the type of transaction

Review by Prasannapathi

**Comment by rajuTK9** [comment]
I have modified the ERD and created a schema diagram. I have uploaded both.

In the new ERD and Schema, I have ensured that it follows the `3rd Normal Form of Normalization rules.`

You can also check the schema diagram [here](https://dbdiagram.io/d/Dhan-Kharch-650e77c1ffbf5169f0581525) and ERD [here](https://app.diagrams.net/#G1hBxMzOhSzTvOi_uSgjl6yjFw-9rSHw4s).

Here's the [link](https://youtu.be/YmlvwTuJJ6k) for the explanation video.

**Comment by PRASANNAPATHI** [comment]
1. Schema & ERD is good with explanation.
2. For Relational Data Model and Normalization, this is not enough,
    You need to cover the following things.
    a. Explain the basic concept of normalization in general.
    b. Showcase that your schema/tables follows Normalization and ACID properties.
    c. Explain how your schema/tables is normalized, in detail.

This PR is now evaluated only for Schema & ERD,
you can add Relational Data Model & Normalization is next PR.

You can merge it now for Schema & ERD.

**Comment by rajuTK9** [comment]
Thanks for your feedback. I will be covering Normalization in the next PR.

**Pull request merged**
